<a href="https://colab.research.google.com/github/AnshikaBaghel/AnshikaBaghel/blob/main/operations_in_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [ ]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(x[0])

1


In [ ]:
print(y[2])

[7 8 9]


In [ ]:
print(y[1][0])

4


In [ ]:
type(x)
type(y)

numpy.ndarray

In [ ]:
z=np.array([[2,3],[4,5],[6,7]])
z

array([[2, 3],
       [4, 5],
       [6, 7]])

In [6]:
import numpy as np

In [7]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
b=a[:2,1:3]

In [9]:
print(b)

[[2 3]
 [6 7]]


In [12]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)


In [13]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [17]:
print(x-y)
print(np.subtract(x,y))


[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [18]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [19]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
